### ISSUE TITLE
System.EntryPointNotFoundException

### ISSUE THREAD

**Issue by RosieCode95** [ppy/osu-framework#1059]
Version: #1297

issue persisted on versions i have tested from the last 2 months.
causes instant crash on startup.

Error:
`System.EntryPointNotFoundException: 'Unable to find an entry point named 'SDL_GetGlobalMouseState' in DLL 'SDL2.dll'.'`

`osu\osu\osu-framework\osu.Framework\Input\Handlers\Mouse\OpenTKMouseHandler.cs` Line 45

Trace 
```
Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'SDL_GetGlobalMouseState' in DLL 'SDL2.dll'.
   at OpenTK.Platform.SDL2.SDL.GetGlobalMouseState(Int32& hx, Int32& hy)
   at OpenTK.Platform.SDL2.Sdl2Mouse.GetCursorState() in D:\temp\67d6772\src\OpenTK\Platform\SDL2\Sdl2Mouse.cs:line 125
   at OpenTK.Input.Mouse.GetCursorState() in D:\temp\67d6772\src\OpenTK\Input\Mouse.cs:line 95
   at osu.Framework.Input.Handlers.Mouse.OpenTKMouseHandler.<>c__DisplayClass4_0.<Initialize>b__3() in C:\Users\rose\Documents\GitHub\osu\osu\osu-framework\osu.Framework\Input\Handlers\Mouse\OpenTKMouseHandler.cs:line 45
   at osu.Framework.Threading.ScheduledDelegate.RunTask() in C:\Users\rose\Documents\GitHub\osu\osu\osu-framework\osu.Framework\Threading\Scheduler.cs:line 280
   at osu.Framework.Threading.Scheduler.Update() in C:\Users\rose\Documents\GitHub\osu\osu\osu-framework\osu.Framework\Threading\Scheduler.cs:line 148
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\Users\rose\Documents\GitHub\osu\osu\osu-framework\osu.Framework\Threading\GameThread.cs:line 112
   at osu.Framework.Threading.InputThread.RunUpdate() in C:\Users\rose\Documents\GitHub\osu\osu\osu-framework\osu.Framework\Threading\InputThread.cs:line 22
   at osu.Framework.Platform.GameHost.<Run>b__89_1(Object <p0>, FrameEventArgs <p1>) in C:\Users\rose\Documents\GitHub\osu\osu\osu-framework\osu.Framework\Platform\GameHost.cs:line 351
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseUpdateFrame(Double elapsed, Double& timestamp) in D:\temp\67d6772\src\OpenTK\GameWindow.cs:line 421
   at OpenTK.GameWindow.DispatchUpdateAndRenderFrame(Object sender, EventArgs e) in D:\temp\67d6772\src\OpenTK\GameWindow.cs:line 384
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in D:\temp\67d6772\src\OpenTK\GameWindow.cs:line 343
   at osu.Framework.Platform.GameHost.Run(Game game) in C:\Users\rose\Documents\GitHub\osu\osu\osu-framework\osu.Framework\Platform\GameHost.cs:line 361
   at osu.Game.Program.Main(String[] args) in C:\Users\rose\Documents\GitHub\osu\osu\osu.Game\Program.cs:line 43
The program '[10520] osu!.exe' has exited with code 0 (0x0).
```

no other logs from what i can find, tho can run tests as this is a reproducible issue on my end

**Comment by VPeruS** [comment]
Thanks for feedback, what version of SDL did you use?

**Comment by RosieCode95** [comment]
Windows: `10.0.15063`

i spent like an hr looking up how to get SDL version and i was unable to work out how, i also noted that the `SDL2.DLL` was not in the compiled package nor in the release one from the launcher.

do let me know if there is anything else i can provide (sorry for n00b'ness dont normally deal with C#)

**Comment by VPeruS** [comment]
You can download dll from dsl site and place it to osu.exe. Normally osu doesn't require sdl

**Comment by RosieCode95** [comment]
after manually adding the `SDL2.DLL (SDL2-2.0.5-win32-x64)` to the osu! directory this is the resulting stack from execution

```
'osu!.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'osu!.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\rose\Documents\GitHub\osu\osu\osu.Game\bin\Debug\osu!.exe'. Symbols loaded.
'osu!.exe' (CLR v4.0.30319: osu!.exe): Loaded 'C:\Users\rose\Documents\GitHub\osu\osu\osu.Game\bin\Debug\osu.Framework.dll'. Symbols loaded.
'osu!.exe' (CLR v4.0.30319: osu!.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'osu!.exe' (CLR v4.0.30319: osu!.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'osu!.exe' (CLR v4.0.30319: osu!.exe): Loaded 'C:\Users\rose\Documents\GitHub\osu\osu\osu.Game\bin\Debug\OpenTK.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'osu!.exe' (CLR v4.0.30319: osu!.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'osu!.exe' (CLR v4.0.30319: osu!.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'osu!.exe' (CLR v4.0.30319: osu!.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'osu!.exe' (CLR v4.0.30319: osu!.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'osu!.exe' (CLR v4.0.30319: osu!.exe): Loaded 'C:\Users\rose\Documents\GitHub\osu\osu\osu.Game\bin\Debug\Newtonsoft.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x1e20 has exited with code 0 (0x0).
The program '[7832] osu!.exe' has exited with code 1080890248 (0x406d1388).

```

**Comment by RosieCode95** [comment]
After chatting with @VPeruS this issue was PEBKAC, i had another version of SDL in path that seamed to be conflicting with the game/
