### ISSUE TITLE
Exception on dispose

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1576]
```
System.NullReferenceException: Object reference not set to an instance of an object.
at osu.Framework.Graphics.Drawable.ToSpaceOfOtherDrawable(RectangleF input, IDrawable other)
at osu.Framework.Graphics.Drawable.ToParentSpace(RectangleF input)
at osu.Framework.Graphics.Drawable.get_BoundingBox()
at osu.Framework.Graphics.Drawable.computeRequiredParentSizeToFit()
at osu.Framework.Graphics.Drawable.get_RequiredParentSizeToFit()
at osu.Framework.Graphics.Containers.CompositeDrawable.computeAutoSize()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateAutoSize()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChildrenSizeDependencies()
at osu.Framework.Graphics.Containers.CompositeDrawable.get_Size()
at osu.Framework.Graphics.Drawable.get_DrawSize()
at osu.Framework.Graphics.Drawable.ToString()
at osu.Framework.Graphics.Drawable.set_Parent(CompositeDrawable value)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
at osu.Framework.Graphics.Containers.CompositeDrawable.Dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
at osu.Framework.Graphics.Containers.CompositeDrawable.Dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
at osu.Framework.Graphics.Containers.CompositeDrawable.Dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
at osu.Framework.Graphics.Containers.CompositeDrawable.Dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
at osu.Framework.Graphics.Containers.CompositeDrawable.Dispose(Boolean isDisposing)
at osu.Game.Input.Bindings.DatabasedKeyBindingContainer`1.Dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
at osu.Framework.Graphics.Containers.CompositeDrawable.Dispose(Boolean isDisposing)
at osu.Framework.Input.CustomInputManager.Dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
at osu.Framework.Graphics.Containers.CompositeDrawable.Dispose(Boolean isDisposing)
at osu.Game.Rulesets.UI.RulesetContainer.Dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
at osu.Framework.Graphics.Containers.CompositeDrawable.Dispose(Boolean isDisposing)
at osu.Game.Skinning.LocalSkinOverrideContainer.Dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
at osu.Framework.Graphics.Containers.CompositeDrawable.Dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.EnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
at osu.Framework.Graphics.Containers.CompositeDrawable.Dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
at osu.Framework.Graphics.Drawable.Dispose()
at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<Dispose>b__7_0(Drawable c)
at osu.Framework.Extensions.IEnumerableExtensions.En
```

Can be triggered by entering and exiting song select rapidly.

**Comment by peppy** [comment]
The disposal part of this is osu! side, but the `ToString()` function should be fixed to not fail.
