### ISSUE TITLE
NullReferenceException at InputManager.createDistinctStates

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu-framework#1593]
I couldn't make a small reproducing code but I'm pretty sure about the cause.
I'll try to fix this by rewriting createDistinctStates but I have a question.
Is there any reason of that InputManager.CurrentState.Mouse/Keyboard/JoyPad can be null? I think it can be initialized by default values.
Stack trace:
```
[runtime:important] System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Framework.Input.InputManager.<>c__DisplayClass71_1.<createDistinctStates>b__3(InputState s) in C:\osu\osu-framework\osu.Framework\Input\InputManager.cs:line 886
   at osu.Framework.Input.InputManager.<createDistinctStates>g__createDistinctState|71_0(Action`1 application, <>c__DisplayClass71_0& ) in C:\osu\osu-framework\osu.Framework\Input\InputManager.cs:line 830
   at osu.Framework.Input.InputManager.<createDistinctStates>d__71.MoveNext() in C:\osu\osu-framework\osu.Framework\Input\InputManager.cs:line 884
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at osu.Framework.Input.InputManager.Update() in C:\osu\osu-framework\osu.Framework\Input\InputManager.cs:line 203
   at osu.Game.Rulesets.UI.RulesetInputManager`1.Update() in C:\osu\osu.Game\Rulesets\UI\RulesetInputManager.cs:line 191
   at osu.Framework.Graphics.Drawable.UpdateSubTree() in C:\osu\osu-framework\osu.Framework\Graphics\Drawable.cs:line 365
...
````

**Comment by peppy** [comment]
Could you at very least include a call stack from the exception?
