### ISSUE TITLE
OpenInNativeExplorer is missing UseShellExecute which results in a crash when opening folders

### ISSUE THREAD

**Issue by Criminalllz** [ppy/osu-framework#1639]
I am using dotnet on linux to build and run

Trace:

`Exception has occurred: CLR/System.ComponentModel.Win32Exception
Exception thrown: 'System.ComponentModel.Win32Exception' in System.Diagnostics.Process.dll: 'The FileName property should not be a directory unless UseShellExecute is set.'
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at osu.Framework.Platform.DesktopStorage.OpenInNativeExplorer()
   at osu.Game.OsuGame.<>c__DisplayClass40_0.<forwardLoggedErrorsToNotifications>b__4() in /home/kristian/build/osu/osu.Game/OsuGame.cs:line 423`

**Comment by peppy** [comment]
Already fixed via #1637
