### ISSUE TITLE
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu-framework#1746]
Opening an issue because I'm getting a crash and I'm not sure what exactly causes it. Not sure if I should, as it's happening in my own "for fun project" (I don't see any "guidelines" for issue reporting neither here or in the readme.md).

Vid: https://streamable.com/zumdf

At first I thought the crash happened because of all the `.FlashColour`s below there:
https://github.com/HoutarouOreki/Spejs-Inwejders/blob/cb363017d0143263ee18fcefc959059ecca1d01b/SpejsInwejders.Game/Screens/Play/PlayerShip.cs#L146 

but if I remove the transforms it also happens, except after slightly more time on average. So why does it happen? The logs don't tell me anything.. In debug mode VS just goes into "break mode", as in "the crash happened in external code".

I get 2 types of logs
1:
```log
[...]
30.07.2018 09:51:29: KeyDown (Left) handled by Player (0,0) 1,033x718.
30.07.2018 09:51:30: KeyDown (Left) handled by Player (0,0) 1,033x718.
30.07.2018 09:51:30: KeyDown (Right) handled by Player (0,0) 1,033x718.
30.07.2018 09:51:30: KeyUp (Left) handled by Player (0,0) 1,033x718.
30.07.2018 09:51:31: fatal error:
30.07.2018 09:51:31: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
30.07.2018 09:51:31: at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
30.07.2018 09:51:31: at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
30.07.2018 09:51:31: at osu.Framework.Graphics.Transforms.TransformSequence`1.onTransformAborted()
30.07.2018 09:51:31: at osu.Framework.Graphics.Transforms.Transformable.invokePendingRemovalActions()
30.07.2018 09:51:31: at osu.Framework.Graphics.Transforms.Transformable.UpdateTransforms()
30.07.2018 09:51:31: at osu.Framework.Graphics.Drawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Testing.TestBrowser.ErrorCatchingDelayedLoadWrapper.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 09:51:31: at osu.Framework.Platform.GameHost.UpdateFrame()
30.07.2018 09:51:31: at osu.Framework.Threading.GameThread.ProcessFrame()
30.07.2018 09:51:31: at osu.Framework.Threading.GameThread.runWork()
30.07.2018 09:51:31: at System.Threading.Thread.ThreadMain_ThreadStart()
30.07.2018 09:51:31: at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```
---
2
```
[...]
30.07.2018 10:20:38: KeyUp (Right) handled by Player (0,0) 1,033x718.
30.07.2018 10:20:40: KeyDown (Right) handled by Player (0,0) 1,033x718.
30.07.2018 10:20:40: KeyUp (Left) handled by Player (0,0) 1,033x718.
30.07.2018 10:20:41: KeyDown (Left) handled by Player (0,0) 1,033x718.
30.07.2018 10:20:41: KeyUp (Right) handled by Player (0,0) 1,033x718.
30.07.2018 10:20:41: fatal error:
30.07.2018 10:20:41: System.InvalidOperationException: May not query Value of an invalid Cached.
30.07.2018 10:20:41: at osu.Framework.Caching.Cached`1.get_Value()
30.07.2018 10:20:41: at osu.Framework.Graphics.Drawable.get_DrawInfo()
30.07.2018 10:20:41: at osu.Framework.Graphics.Drawable.Contains(Vector2 screenSpacePos)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.Contains(Vector2 screenSpacePos)
30.07.2018 10:20:41: at osu.Framework.Graphics.Drawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.BuildMouseInputQueue(Vector2 screenSpaceMousePos, List`1 queue)
30.07.2018 10:20:41: at osu.Framework.Input.InputManager.buildMouseInputQueue(InputState state)
30.07.2018 10:20:41: at osu.Framework.Input.InputManager.updateHoverEvents(InputState state)
30.07.2018 10:20:41: at osu.Framework.Input.InputManager.Update()
30.07.2018 10:20:41: at osu.Framework.Input.PassThroughInputManager.Update()
30.07.2018 10:20:41: at osu.Framework.Graphics.Drawable.UpdateSubTree()
30.07.2018 10:20:41: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
30.07.2018 10:20:41: at osu.Framework.Platform.GameHost.UpdateFrame()
30.07.2018 10:20:41: at osu.Framework.Threading.GameThread.ProcessFrame()
30.07.2018 10:20:41: at osu.Framework.Threading.GameThread.runWork()
30.07.2018 10:20:41: at System.Threading.Thread.ThreadMain_ThreadStart()
30.07.2018 10:20:41: at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

What do these exceptions mean, so that I could correct whatever I'm doing wrong? Why is there mouse input in the 2nd one? Again sorry if we're not supposed to open issues about things like this.

**Comment by jorolf** [comment]
You shouldn't add or remove transforms from a thread that's not the update thread. Instead of using a Timer in Line 85 you should use the scheduler

**Comment by HoutarouOreki** [comment]
It seems using that Threading.Timer was indeed the problem - no more crashes. Thanks a lot
