### ISSUE TITLE
DrawVisualiser exceptions occur randomly

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1926]
Happen very randomly:

```
System.ObjectDisposedException: Attempting to load an already disposed drawable.
Object name: 'PropertyDisplay+PropertyItem'.
   at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
   at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
   at osu.Framework.Graphics.Containers.CompositeDrawable.checkChildLife(Drawable child)
   at osu.Framework.Graphics.Containers.CompositeDrawable.checkChildrenLife()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateChildrenLife()
   at osu.Framework.Graphics.Containers.FlowContainer`1.UpdateChildrenLife()
```

When exiting song select with property display active.

```
Unhandled Exception: An unhandled error has occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Framework.Graphics.Visualisation.DrawVisualiser.recycleVisualisers()
   at osu.Framework.Graphics.Containers.VisibilityContainer.updateState()
   at osu.Framework.Game.OnPressed(FrameworkAction action)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at osu.Framework.Input.Bindings.KeyBindingContainer`1.PropagatePressed(IEnumerable`1 drawables, T pressed, Single scrollAmount, Boolean isPrecise)
   at osu.Framework.Input.Bindings.KeyBindingContainer`1.handleNewPressed(InputState state, InputKey newKey, Boolean repeat, Nullable`1 scrollDelta, Boolean isPrecise)
   at osu.Framework.Input.Bindings.KeyBindingContainer`1.OnKeyDown(InputState state, KeyDownEventArgs args)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at osu.Framework.Input.InputManager.PropagateKeyDown(IEnumerable`1 drawables, InputState state, KeyDownEventArgs args)
   at osu.Framework.Input.InputManager.HandleKeyboardKeyStateChange(InputState state, Key key, ButtonStateChangeKind kind)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
```

When attempting to close the draw visualiser.

**Comment by smoogipoo** [comment]
As an update, I've also managed to reproduce the following by dynamic compiling with the draw vis active:

```
Unhandled Exception: [runtime:error] 12/14/2018 05:06:37: An unhandled error has occurred.
[runtime:error] 12/14/2018 05:06:37: System.ObjectDisposedException: Disposed Drawables may never be in the scene graph.
[runtime:error] 12/14/2018 05:06:37: Object name: 'VisualisedDrawable'.
[runtime:error] 12/14/2018 05:06:37: at osu.Framework.Graphics.Drawable.UpdateSubTree() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Drawable.cs:line 393
[runtime:error] 12/14/2018 05:06:37: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 686
[runtime:error] 12/14/2018 05:06:37: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 703
[runtime:error] 12/14/2018 05:06:37: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 703
[runtime:error] 12/14/2018 05:06:37: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 703
[runtime:error] 12/14/2018 05:06:37: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 703
[runtime:error] 12/14/2018 05:06:37: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 703
[runtime:error] 12/14/2018 05:06:37: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 703
```
