### ISSUE TITLE
Disposed vertex buffer attempted to be bound

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2239]
```
[runtime:error] 3/13/19 5:23:50 AM: System.ObjectDisposedException: Can not bind disposed vertex buffers.
[runtime:error] 3/13/19 5:23:50 AM: Object name: 'osu.Framework.Graphics.OpenGL.Buffers.QuadVertexBuffer`1[osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D]'.
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.OpenGL.Buffers.VertexBuffer`1.Bind(Boolean forRendering) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\VertexBuffer.cs:line 76
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.OpenGL.Buffers.QuadVertexBuffer`1.Bind(Boolean forRendering) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\QuadVertexBuffer.cs:line 62
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.OpenGL.Buffers.VertexBuffer`1.UpdateRange(Int32 startIndex, Int32 endIndex) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\VertexBuffer.cs:line 128
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.Batches.VertexBatch`1.Draw() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Batches\VertexBatch.cs:line 127
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.OpenGL.GLWrapper.FlushCurrentBatch() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\GLWrapper.cs:line 482
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.OpenGL.GLWrapper.BindTexture(TextureGL texture) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\GLWrapper.cs:line 233
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.OpenGL.Textures.TextureGLSingle.Bind() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Textures\TextureGLSingle.cs:line 316
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.Sprites.SpriteText.SpriteTextDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Sprites\SpriteText_DrawNode.cs:line 34
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawNode.cs:line 201
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawNode.cs:line 201
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawNode.cs:line 201
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawNode.cs:line 201
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Platform.GameHost.DrawFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 382
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Threading.GameThread.ProcessFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 140
[runtime:error] 3/13/19 5:23:50 AM: at osu.Framework.Threading.GameThread.runWork() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 110
System.ObjectDisposedException: Can not bind disposed vertex buffers.
Object name: 'osu.Framework.Graphics.OpenGL.Buffers.QuadVertexBuffer`1[osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D]'.
   at osu.Framework.Graphics.OpenGL.Buffers.VertexBuffer`1.Bind(Boolean forRendering) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\VertexBuffer.cs:line 76
   at osu.Framework.Graphics.OpenGL.Buffers.QuadVertexBuffer`1.Bind(Boolean forRendering) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\QuadVertexBuffer.cs:line 62
   at osu.Framework.Graphics.OpenGL.Buffers.VertexBuffer`1.UpdateRange(Int32 startIndex, Int32 endIndex) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Buffers\VertexBuffer.cs:line 128
   at osu.Framework.Graphics.Batches.VertexBatch`1.Draw() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Batches\VertexBatch.cs:line 127
   at osu.Framework.Graphics.OpenGL.GLWrapper.FlushCurrentBatch() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\GLWrapper.cs:line 482
   at osu.Framework.Graphics.OpenGL.GLWrapper.BindTexture(TextureGL texture) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\GLWrapper.cs:line 233
   at osu.Framework.Graphics.OpenGL.Textures.TextureGLSingle.Bind() in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\OpenGL\Textures\TextureGLSingle.cs:line 316
   at osu.Framework.Graphics.Sprites.SpriteText.SpriteTextDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Sprites\SpriteText_DrawNode.cs:line 34
   at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawNode.cs:line 201
   at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawNode.cs:line 201
   at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawNode.cs:line 201
   at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction) in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Containers\CompositeDrawNode.cs:line 201
   at osu.Framework.Platform.GameHost.DrawFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 382
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 140
   at osu.Framework.Threading.GameThread.runWork() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Threading.ScheduledDelegate.RunTask() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\Scheduler.cs:line 284
   at osu.Framework.Threading.Scheduler.Update() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\Scheduler.cs:line 155
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 136
   at osu.Framework.Platform.GameHost.<Run>b__103_1(Object <p0>, FrameEventArgs <p1>) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 521
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 524
   at osu.Desktop.Program.Main(String[] args) in /Users/dean/Projects/osu/osu.Desktop/Program.cs:line 46
```

Happened while browsing osu!direct

**Comment by smoogipoo** [comment]
I'm fairly certain at this point this was fixed by #2260 . Closing.
