### ISSUE TITLE
DelayedLoadUnloadWrapper should support lifetimes

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#2610]
A simple way to get this working is to store the given lifetime locally as a fallback, something like:

```csharp
public override double LifetimeStart
{
    get => base.Content?.LifetimeStart ?? lifetimeStart;
    set
    {
        if (base.Content != null)
            base.Content.LifetimeStart = value;
        lifetimeStart = value;
    }
}

private double lifetimeEnd = double.MaxValue;

public override double LifetimeEnd
{
    get => base.Content?.LifetimeEnd ?? lifetimeEnd;
    set
    {
        if (base.Content != null)
            base.Content.LifetimeEnd = value;
        lifetimeEnd = value;
    }
}
```

And to set the lifetime when new content is loaded.

**Comment by peppy** [comment]
This becomes a pretty serious issue when you see this:

```
2019-07-02 12:39:28: System.NotSupportedException: Specified method is not supported.
2019-07-02 12:39:28: at osu.Framework.Graphics.Containers.DelayedLoadUnloadWrapper.set_LifetimeEnd(Double value)
2019-07-02 12:39:28: at osu.Framework.Graphics.Drawable.Expire(Boolean calculateLifetimeStart)
2019-07-02 12:39:28: at osu.Framework.Graphics.Transforms.Transformable.invokePendingRemovalActions()
2019-07-02 12:39:28: at osu.Framework.Graphics.Transforms.Transformable.UpdateTransforms()
2019-07-02 12:39:28: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2019-07-02 12:39:28: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2019-07-02 12:39:28: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2019-07-02 12:39:28: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2019-07-02 12:39:28: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2019-07-02 12:39:28: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```
