### ISSUE TITLE
ArgumentNullException when dragging the window title

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#2809]
```
[runtime:error] 2019-08-30 03:33:18: System.ArgumentNullException: Value cannot be null.
[runtime:error] 2019-08-30 03:33:18: Parameter name: first
[runtime:error] 2019-08-30 03:33:18: at System.Linq.Enumerable.Intersect[TSource](IEnumerable`1 first, IEnumerable`1 second)
[runtime:error] 2019-08-30 03:33:18: at osu.Framework.Input.MouseButtonEventManager.HandleMouseClick(InputState state) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Input/MouseButtonEventManager.cs:line 194
[runtime:error] 2019-08-30 03:33:18: at osu.Framework.Input.MouseButtonEventManager.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind, Double currentTime) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Input/MouseButtonEventManager.cs:line 153
[runtime:error] 2019-08-30 03:33:18: at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Input/InputManager.cs:line 483
System.ArgumentNullException: Value cannot be null.
Parameter name: first
   at System.Linq.Enumerable.Intersect[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at osu.Framework.Input.MouseButtonEventManager.HandleMouseClick(InputState state) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Input/MouseButtonEventManager.cs:line 194
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind, Double currentTime) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Input/MouseButtonEventManager.cs:line 153
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Input/InputManager.cs:line 483
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Input/InputManager.cs:line 445
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Input/UserInputManager.cs:line 53
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler) in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Input/StateChanges/ButtonInput.cs:line 74
   at osu.Framework.Input.InputManager.Update() in /Users/smoogipoo/Repos/osu-framework/osu.Framework/Input/InputManager.cs:line 238
```

**Comment by smoogipoo** [comment]
Regressed in https://github.com/ppy/osu-framework/pull/2805
