### ISSUE TITLE
My game crash in start

### ISSUE THREAD

**Issue by maksim789456** [ppy/osu-framework#2997]
After updating the osu-framework, crashes began. I have absolutely no idea what can be done😔
<details><summary>Crash report</summary>

Unhandled Exception: System.InvalidOperationException: This operation must be performed on the same thread as that represented by the Thread instance.
   at System.Threading.Thread.RequireCurrentThread()
   at osu.Framework.Platform.GameHost.<>c__DisplayClass130_3.<SetupConfig>b__11() in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 805
   at osu.Framework.Threading.ScheduledDelegate.RunTask() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\Scheduler.cs:line 347
   at osu.Framework.Threading.Scheduler.Update() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\Scheduler.cs:line 113
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\projects\osu-framework-a4n7e\osu.Framework\Threading\GameThread.cs:line 136
   at osu.Framework.Platform.GameHost.<Run>b__113_1(Object <p0>, FrameEventArgs <p1>) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 546
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game) in C:\projects\osu-framework-a4n7e\osu.Framework\Platform\GameHost.cs:line 549
   at TestGame.Program.Main(String[] args) in /home/st/TestGame/TestGame/Program.cs:line 28

**Comment by bdach** [comment]
Try updating your framework-utilising project to .NET Core 3.0.

Version 2019.1010.0 (or merge of #2829) bumped Core version to 3.0, which fixed not being able to set culture on unstarted threads (see dotnet/corefx#33574). #2895 then added support for setting thread locale using the framework locale setting, which exposes this bug on earlier Core versions. This should probably be documented somewhere for posterity.

**Comment by maksim789456** [comment]
That helped. Thank you!
