### ISSUE TITLE
Unhandled Error when creating test game

### ISSUE THREAD

**Issue by Kronos019** [ppy/osu-framework#3002]
After recreating the code from "Setting up your first project" in the wiki and running it, it gives this unhandled error
```[runtime:error] 2019-11-15 02:59:12: An unhandled error has occurred.
[runtime:error] 2019-11-15 02:59:12: System.ArgumentException: Illegal characters in path.
[runtime:error] 2019-11-15 02:59:12: at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
[runtime:error] 2019-11-15 02:59:12: at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
[runtime:error] 2019-11-15 02:59:12: at osu.Framework.Platform.NativeStorage.GetFullPath(String path, Boolean createIfNotExisting)
[runtime:error] 2019-11-15 02:59:12: at osu.Framework.Platform.Storage.GetStorageForDirectory(String path)
[runtime:error] 2019-11-15 02:59:12: at osu.Framework.Platform.GameHost.SetupForRun()
[runtime:error] 2019-11-15 02:59:12: at osu.Framework.Platform.Windows.WindowsGameHost.SetupForRun()
[runtime:error] 2019-11-15 02:59:12: at osu.Framework.Platform.GameHost.Run(Game game)
[runtime:error] 2019-11-15 02:59:12: at OsuFrameworkTest.Program.Main() in C:\Users\<User>\source\repos\OsuFrameworkTest\OsuFrameworkTest\Program.cs:line 18

**Comment by smoogipoo** [comment]
May have to debug this one and see what the value of `path` is in `NativeStorage.GetFullPath`.

**Comment by Kronos019** [comment]
it says the value is "logs\\"

**Comment by smoogipoo** [comment]
What about the value of `resolvedPath`?

**Comment by Kronos019** [comment]
the exception occurs before `resolvedPath` is assigned

**Comment by smoogipoo** [comment]
Hmm in that case, need the values of `BasePath`, `BaseName` and `SubDirectory`.

**Comment by Kronos019** [comment]
Its not able to access those values. Also, the exception seems to occur on line 56

**Comment by Kronos019** [comment]
i somehow didnt have .net core 3.0
