### ISSUE TITLE
Log Overlay cannot be opened via the settings checkbox

### ISSUE THREAD

**Issue by edisonlee55** [ppy/osu-framework#3069]
**Describe the bug:** 
Also, enable only the "Show log overlay" option won't open Log Overlay, either.

**In order to open the Log Overlay correctly, we must first enable the "Show log overlay" option and then press the shortcut key (`Control-F10`).**

**Comment by UselessToucan** [comment]
What is the correct behaviour for this kind of situations? I am pretty sure that the Log Overlay is not the only case. Should we silently ignore a shortcut press? Or display some notification like "Feature X is disabled"?

**Comment by smoogipoo** [comment]
There doesn’t need to be special handling or a “feature disabled” message because the framework shouldn’t be throwing exceptions in the first place.

**Comment by edisonlee55** [comment]
Draw Visualizer shortcut (`Ctrl-F1 `) doesn't work on my side, either.
But it's not throwing any exceptions.

**Comment by swoolcock** [comment]
@edisonlee55 I'm guessing you're running Parsec and encountering this issue: #3043

**Comment by edisonlee55** [comment]
I have Parsec, but not running.
As you have mentioned in that issue, macOS default system shortcuts causing conflict with Draw Visualizer shortcut.
After turning off the system shortcut that binds to `Ctrl-F1` resolves the issue.

**Comment by edisonlee55** [comment]
I could still reproduce the Log Overlay shortcut error in  `2019.1205.0`.

Logs:
```
2019-12-05 01:49:07: Unhandled exception has been allowed with 0 more allowable exceptions .
2019-12-05 01:49:07: An unhandled error has occurred.
2019-12-05 01:49:07: System.NullReferenceException: Object reference not set to an instance of an object.
2019-12-05 01:49:07: at osu.Framework.Graphics.Visualisation.LogOverlay.setHoldState(Boolean controlPressed)
2019-12-05 01:49:07: at osu.Framework.Graphics.Visualisation.LogOverlay.PopOut()
2019-12-05 01:49:07: at osu.Framework.Graphics.Containers.VisibilityContainer.LoadAsyncComplete()
2019-12-05 01:49:07: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2019-12-05 01:49:07: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2019-12-05 01:49:07: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](IEnumerable`1 components, IReadOnlyDependencyContainer dependencies, Boolean isAsyncContext)
2019-12-05 01:49:07: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_0`1.<LoadComponentsAsync>b__1()
2019-12-05 01:49:07: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2019-12-05 01:49:07: --- End of stack trace from previous location where exception was thrown ---
2019-12-05 01:49:07: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2019-12-05 01:49:07: --- End of stack trace from previous location where exception was thrown ---
2019-12-05 01:49:07: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_2`1.<LoadComponentsAsync>b__4()
2019-12-05 01:49:07: at osu.Framework.Threading.ScheduledDelegate.RunTask()
2019-12-05 01:49:07: at osu.Framework.Threading.Scheduler.Update()
2019-12-05 01:49:07: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2019-12-05 01:49:07: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2019-12-05 01:49:07: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2019-12-05 01:49:07: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2019-12-05 01:49:07: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2019-12-05 01:49:07: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2019-12-05 01:49:07: at osu.Framework.Platform.GameHost.UpdateFrame()
2019-12-05 01:49:07: at osu.Framework.Threading.GameThread.ProcessFrame()
2019-12-05 01:49:07: at osu.Framework.Threading.GameThread.runWork()
```

**Comment by smoogipoo** [comment]
Reopening since the error part of it has been fixed, but the config part of it hasn't.

**Comment by edisonlee55** [comment]
There is no longer any error thrown but still has a bug in osu!lazer `2019.1213.0`.

**The log overlay will not display after interlacing between both shortcut key and setting option.**

For instance:
Using the shortcut key to open log overlay and use the setting option to close it. After doing it, the log overlay wouldn't be able to open with both shortcut key or setting option again.

**Comment by peppy** [comment]
How are you testing this?

**Comment by edisonlee55** [comment]
@peppy 

Steps of my testing:
1. Open log overlay by using shortcut key
2. Close log overlay from the in game settings
3. Try to open log overlay again with either shortcut or in game settings, you will find out that log overlay no longer works.

**Comment by peppy** [comment]
I've tried to reproduce this but can't.

**Comment by edisonlee55** [comment]
I have also reproduce this issue from a clean Windows VM.
And I think it's no longer relevant to interlacing, but the log itself.

The log seems not coming out at all.
It will only display "The debug log overlay is currently being displayed..." and nothing comes out after.
<img width="396" alt="screenshot" src="https://user-images.githubusercontent.com/5277788/70910214-378ede00-204a-11ea-8a53-50e4e74a7834.png">

**Comment by smoogipoo** [comment]
There is very little that is logged on release builds - mostly errors.

**Comment by edisonlee55** [comment]
Oh, I see.
Is there any option to enable verbose logging on release builds?

**Comment by smoogipoo** [comment]
You will have to compile in debug for that.

**Comment by edisonlee55** [comment]
Got it, thanks for your explanation.
