### ISSUE TITLE
Opening draw visualiser and global statistics and clicking randomly hits assert

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#3349]
```
[runtime] 2020-03-09 10:10:45 [error]: NUnit.Framework.AssertionException: Cyclic invocation of computeCharacters()!:
[runtime] 2020-03-09 10:10:45 [error]: at osu.Framework.Logging.ThrowingTraceListener.Fail(String message1, String message2) in /Users/dean/Projects/osu-framework/osu.Framework/Logging/ThrowingTraceListener.cs:line 25
[runtime] 2020-03-09 10:10:45 [error]: at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
[runtime] 2020-03-09 10:10:45 [error]: at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)
[runtime] 2020-03-09 10:10:45 [error]: at osu.Framework.Graphics.Sprites.SpriteText.computeCharacters() in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Sprites/SpriteText.cs:line 451
[runtime] 2020-03-09 10:10:45 [error]: at osu.Framework.Graphics.Sprites.SpriteText.get_Size() in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Sprites/SpriteText.cs:line 364
[runtime] 2020-03-09 10:10:45 [error]: at osu.Framework.Graphics.Drawable.get_DrawSize() in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Drawable.cs:line 791
[runtime] 2020-03-09 10:10:45 [error]: at osu.Framework.Graphics.Drawable.get_LayoutSize() in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Drawable.cs:line 829
[runtime] 2020-03-09 10:10:45 [error]: at osu.Framework.Graphics.Drawable.get_LayoutRectangle() in /Users/dean/Projects/osu-framework/osu.Framework/Graphics/Drawable.cs:line 852
```

**Comment by peppy** [comment]
As this requires very specific usage to reproduce (and only happens in debug) lowering the priority for now.
