### ISSUE TITLE
Excessive logging while Performance Overlay is visible can cause high memory traffic

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu-framework#3768]
When using the global statistics while playing mania, there are a lot of stutters and frame drops, extremely high RAM usage and game instability. I can't check for issues in my performance log since it's 1.6 GB because of this bug and notepad doesn't like that. I don't seem to have this issue while playing osu!standard.

https://youtu.be/QjSQNLuKJJs (the RAM does seem to clear at the end of the video causing a massive frame drop, it does go up again after that if I play more mania)

version: 2020.725.0

logs: https://www112.zippyshare.com/v/BnkTkIiU/file.html

**Comment by peppy** [comment]
Are you sure this isn't the same issue that I fixed relating to memory usage of this dialog?

**Comment by smoogipoo** [comment]
Were your fixes in 2020.725.0? If so, then it's not the same issue (or your fix didn't work).

**Comment by smoogipoo** [comment]
I assume https://github.com/ppy/osu-framework/pull/3741 is what you're talking about? That's an ephemeral allocation, whereas this issue is not.

**Comment by peppy** [comment]
https://github.com/ppy/osu-framework/pull/3718 this one, but that should already be merged.

**Comment by peppy** [comment]
The major issue here looks to be the amount of logging output:

```
2020-07-29 02:40:14 [verbose]: 
2020-07-29 02:40:14 [verbose]: Resource lightingN-5:wrap-0-0 was retrieved from a TextureStore on a non-background thread.
2020-07-29 02:40:14 [verbose]: at osu.Framework.Graphics.Textures.TextureStore.Get(String name, WrapMode wrapModeS, WrapMode wrapModeT)
2020-07-29 02:40:14 [verbose]: at osu.Game.Skinning.LegacySkin.GetTexture(String componentName, WrapMode wrapModeS, WrapMode wrapModeT)
2020-07-29 02:40:14 [verbose]: at osu.Game.Skinning.SkinProvidingContainer.GetTexture(String componentName, WrapMode wrapModeS, WrapMode wrapModeT)
2020-07-29 02:40:14 [verbose]: at osu.Game.Skinning.LegacySkinExtensions.<>c__DisplayClass1_0.<<GetAnimation>g__getTextures|0>d.MoveNext()
2020-07-29 02:40:14 [verbose]: at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
```

around 500mb in a few seconds for me.

**Comment by peppy** [comment]
Not sure what the correct fix is here. Do we want to limit the logger output to some same limit?
