### ISSUE TITLE
Changing thread mode while in sdl freezes the game

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu-framework#3879]
**Describe the crash:** dont know if this should be a framework issue or not. when osu is run with the --sdl parameters, and changing the thread mode (either single to multi and vise versa) freezes the game while the sound and game still somewhat responds (evident by pressing ctrl + o for settings and the pop up open sound can be heard and pressing p key to go to song select and the song plays for like 3 seconds and crashes immediately). i dont know if this is hardware since when osu is restarted, the game works and even switches the thread to the one you switched (e.g. pre-crash: multi Switched to single, when restarted post-crash: single

**Screenshots or videos showing encountered issue:** 
https://drive.google.com/file/d/1UMt-dDiMl-j5JZsHvddLXp0zrF-joXjm/view?usp=sharing

**osu!lazer version:** 2020.903.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/5193965/runtime.log)

**Computer Specifications:** 
Device name	PC
Processor	Intel(R) Pentium(R) CPU        P6200  @ 2.13GHz   2.13 GHz
Installed RAM	6.00 GB (5.80 GB usable)
GPU         First gen intel hd graphics
System type	64-bit operating system, x64-based processor

**Comment by peppy** [comment]
cc @swoolcock

**Comment by swoolcock** [comment]
This is likely due to the way threading is currently handled with the SDL backend.  Will look into it.

**Comment by enoslayd** [comment]
before i noticed this im trying the sdl fullscreen pr and tought this maybe because of that pr so i tried in the latest release and this happeded

**Comment by swoolcock** [comment]
Unrelated to the fullscreen PR, this is an existing issue.

**Comment by enoslayd** [comment]
Ok thanks

**Comment by swoolcock** [comment]
Cannot reproduce on macOS using `master`, `2020.903.0`, or #3781
A second look into the SDL backend shows that its handling of window/main thread should be identical to osuTK.

The bigger problem is this in runtime.log:

> 2020-09-09 09:03:53 [error]: An unhandled error has occurred.
2020-09-09 09:03:53 [error]: System.InvalidOperationException: Can not obtain ID of a texture before uploading it.
2020-09-09 09:03:53 [error]: at osu.Framework.Graphics.OpenGL.Textures.TextureGLSingle.get_TextureId()
2020-09-09 09:03:53 [error]: at osu.Framework.Graphics.OpenGL.GLWrapper.BindTexture(TextureGL texture, TextureUnit unit, WrapMode wrapModeS, WrapMode wrapModeT)
2020-09-09 09:03:53 [error]: at osu.Framework.Graphics.OpenGL.Textures.TextureGLSingle.DoUpload(ITextureUpload upload, IntPtr dataPointer)
2020-09-09 09:03:53 [error]: at osu.Framework.Graphics.OpenGL.Textures.TextureGLSingle.Upload()
2020-09-09 09:03:53 [error]: at osu.Framework.Graphics.OpenGL.GLWrapper.Reset(Vector2 size)
2020-09-09 09:03:53 [error]: at osu.Framework.Platform.GameHost.DrawFrame()
2020-09-09 09:03:53 [error]: at osu.Framework.Threading.GameThread.ProcessFrame()

My guess is that it's something to do with OpenGL context switching in Windows.
Can someone else please attempt to reproduce this on Windows? (Linux would be nice too, if possible)

**Comment by smoogipoo** [comment]
Can't replicate on Linux, can replicate on Windows.

When switching from Multithreaded -> Singlethreaded -> Multithreaded, I actually crash with the following error (on the last switch):
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at osu.Framework.Graphics.OpenGL.GLWrapper.BindFrameBuffer(Int32)
   at osu.Framework.Graphics.OpenGL.GLWrapper.Reset(osuTK.Vector2)
   at osu.Framework.Threading.DrawThread.OnInitialize()
   at osu.Framework.Threading.GameThread.Initialize(Boolean)
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

When switching from Singlethreaded -> Multithreaded, I can replicate the graphics lockup in the OP. There's no output in the `runtime.log` for me.

**Comment by swoolcock** [comment]
It appears that on Windows, `SDL_GL_MakeCurrent` will not allow a thread to take ownership of a context if it currently belongs to another thread.  macOS and Linux can call `SDL_GL_MakeCurrent` to "change" ownership, but on Windows we must first call it with `IntPtr.Zero` to release ownership before another thread can take it.

With the SDL backend, we create the GL context on the main thread, then release ownership and allow the draw thread to take it.  This is why this exists:
https://github.com/ppy/osu-framework/blob/master/osu.Framework/Platform/Sdl/PassthroughGraphicsBackend.cs#L93

If we forcefully clear ownership of the context when changing threading models, the draw thread should automatically pick it up from the change in #3721

**Comment by peppy** [comment]
Yep, that is correct. And that's already being done correctly on non-SDL, so may want to track down where that's occurring.
