### ISSUE TITLE
Do not make MIDI Device support mandatory in Linux

### ISSUE THREAD

**Issue by sr229** [ppy/osu-framework#4324]
Currently, if a Linux user doesn't have `snd_seq` enabled, it will not allow any project using osu!framework to work. MIDI devices should not be a hard requirement since not all projects even need MIDI device support, and this does hamper development with virtualized Linux instances based from WSL2 where `snd_seq` is not included.

**Comment by peppy** [comment]
Care to attach logs or anything really?

**Comment by sr229** [comment]
So far when running on WSL2 this is what gets returned: 
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
[runtime] 2021-03-31 03:27:36 [error]: Couldn't list input devices. Is libasound2-dev installed?
[runtime] 2021-03-31 03:27:36 [error]: System.TypeInitializationException: The type initializer for 'Commons.Music.Midi.MidiAccessManager' threw an exception.
[runtime] 2021-03-31 03:27:36 [error]: ---> AlsaSharp.AlsaException: ALSA exception (error code = -2) : No such file or directory
[runtime] 2021-03-31 03:27:36 [error]: at AlsaSharp.AlsaSequencer..ctor(AlsaIOType ioType, AlsaIOMode ioMode, String driverName)
[runtime] 2021-03-31 03:27:36 [error]: at Commons.Music.Midi.Alsa.AlsaMidiAccess..ctor()
[runtime] 2021-03-31 03:27:36 [error]: at Commons.Music.Midi.MidiAccessManager.InitializeDefault()
[runtime] 2021-03-31 03:27:36 [error]: at Commons.Music.Midi.MidiAccessManager..cctor()
[runtime] 2021-03-31 03:27:36 [error]: --- End of inner exception stack trace ---
[runtime] 2021-03-31 03:27:36 [error]: at Commons.Music.Midi.MidiAccessManager.get_Default()
[runtime] 2021-03-31 03:27:36 [error]: at osu.Framework.Input.Handlers.Midi.MidiHandler.refreshDevices()
[runtime] 2021-03-31 03:27:38 [error]: An unhandled error has occurred.
[runtime] 2021-03-31 03:27:38 [error]: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
[runtime] 2021-03-31 03:27:38 [error]: at System.Char.IsDigit(String s, Int32 index)
[runtime] 2021-03-31 03:27:38 [error]: at osu.Framework.Platform.PassthroughGraphicsBackend.<>c.<getVersionNumberSubstring>b__25_0(String s)
[runtime] 2021-03-31 03:27:38 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
[runtime] 2021-03-31 03:27:38 [error]: at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
[runtime] 2021-03-31 03:27:38 [error]: at osu.Framework.Platform.PassthroughGraphicsBackend.getVersionNumberSubstring(String version)
[runtime] 2021-03-31 03:27:38 [error]: at osu.Framework.Platform.PassthroughGraphicsBackend.Initialise(IWindow window)
[runtime] 2021-03-31 03:27:38 [error]: at osu.Framework.Platform.SDL2.SDL2GraphicsBackend.Initialise(IWindow window)
[runtime] 2021-03-31 03:27:38 [error]: at osu.Framework.Platform.SDL2DesktopWindow.Create()
[runtime] 2021-03-31 03:27:38 [error]: at osu.Framework.Platform.GameHost.Run(Game game)
[runtime] 2021-03-31 03:27:38 [error]: at Hololive.Game.Program.Main() in /mnt/d/Ayane/projects/shining-virtual-stars/Hololive.Game/Program.cs:line 11
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Char.IsDigit(String s, Int32 index)
   at osu.Framework.Platform.PassthroughGraphicsBackend.<>c.<getVersionNumberSubstring>b__25_0(String s)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Platform.PassthroughGraphicsBackend.getVersionNumberSubstring(String version)
   at osu.Framework.Platform.PassthroughGraphicsBackend.Initialise(IWindow window)
   at osu.Framework.Platform.SDL2.SDL2GraphicsBackend.Initialise(IWindow window)
   at osu.Framework.Platform.SDL2DesktopWindow.Create()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at Hololive.Game.Program.Main() in /mnt/d/Ayane/projects/shining-virtual-stars/Hololive.Game/Program.cs:line 11
```

Ths SDL2 errors is something I can fix later on, but MIDI throws as a unhandled exception when `/dev/snd/seq` is not found, which is the sequencer module.

**Comment by peppy** [comment]
The midi error is not fatal. Please check the code.

**Comment by smoogipoo** [comment]
The fatal error is actually listed in that log - it's the lack of a GL context.

**Comment by peppy** [comment]
Yep. We can probably provide better messaging for the gl context failure, rather than dying on a string operation.
