### ISSUE TITLE
Crash with draw visualiser open

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4429]
Reproduction:

- Run `TestSceneBeatmapInfoWedge`
- Open draw visualiser and target text
- Run step `select no beatmaps available`

```csharp
[runtime] 2021-05-04 04:43:02 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Drawable.ToSpaceOfOtherDrawable(RectangleF input, IDrawable other)
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Drawable.get_BoundingBox()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.get_BoundingBox()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Drawable.computeRequiredParentSizeToFit()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Drawable.get_RequiredParentSizeToFit()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.computeAutoSize()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.updateAutoSize()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.updateChildrenSizeDependencies()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.get_Size()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Drawable.get_DrawSize()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Visualisation.VisualisedDrawable.updateSpecifics()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Visualisation.VisualisedDrawable.Update()
[runtime] 2021-05-04 04:43:02 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
```

**Comment by smoogipoo** [comment]
I can't repro, am I doing something wrong?: https://drive.google.com/file/d/1pa5U5het6_gRtqJff0xb1oepq_MtewX_/view?usp=sharing

Does this happen every time?

**Comment by peppy** [comment]
You *might* need to be on https://github.com/ppy/osu/pull/12503. Not sure if there's a logical error in that PR or not yet.

**Comment by smoogipoo** [comment]
I also can't repro on the latest commit of that PR.

My suspicion it's a race condition caused by `CompositeDrawable.LoadAsyncComplete()` as that's the only thing that updates `AliveInternalChildren` asynchronously. The path would be something like:

```
In LoadAsyncComplete():
    - Make child alive
    - Invoke ChildBecameAlive event. Somehow add a child to the drawvis tree that bypasses the update-thread guard.
    - Invoke RemoveInternal()

In UpdateSubTree():
    - Update visualised drawable to get to the get_Size failure point in OP.

In LoadAsyncComplete():
    - cont. from above
    - Remove child from aliveInternalChildren.
    - Invoke ChildDied event. Somehow remove the child from the drawvis tree, again bypassing the update-thread guard.
    - Set parent null

In UpdateSubTree():
    - cont. from above
    - Call ToSpaceOfOtherDrawable(), crash.
```

Not sure. Was this a reliable repro at the time? Even if the above was the case (which has issues in being possible), it's an extremely timing-dependent scenario.

**Comment by peppy** [comment]
yeah it's 100% for me:


https://user-images.githubusercontent.com/191335/117123899-95a09a80-add2-11eb-81e2-52218dcfd650.mp4
