### ISSUE TITLE
Dynamic compilation attempts to resolve a version of `Nuget.ProjectModel` that doesn't exist

### ISSUE THREAD

**Issue by jai-x** [ppy/osu-framework#4512]
## System
dotnet version: 5.0.301
os: Arch Linux x64
osu-framework version: 2021.611.0
have I run donet restore: yes

## Reproduction
Creating a new project from the templates  and running the visual test will result in a error when trying to run dynamic compilation. It attempts to resolve `Nuget.ProjectModel Version=5.10.0.7240` which doesn't exist according to it's gallery page: https://www.nuget.org/packages/NuGet.ProjectModel/

Attempted to resolve by manually installing the latest preview version of `Nuget.ProjectModel` but did not seem to fix the issue.

## Stacktrace 
```log
[runtime] 2021-06-14 12:26:05 [error]: Error with dynamic compilation!
[runtime] 2021-06-14 12:26:05 [error]: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.ProjectModel, Version=5.10.0.7240, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
[runtime] 2021-06-14 12:26:05 [error]:
[runtime] 2021-06-14 12:26:05 [error]: File name: 'NuGet.ProjectModel, Version=5.10.0.7240, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[runtime] 2021-06-14 12:26:05 [error]: at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
[runtime] 2021-06-14 12:26:05 [error]: at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
[runtime] 2021-06-14 12:26:05 [error]: at System.RuntimeType.get_DeclaringType()
[runtime] 2021-06-14 12:26:05 [error]: at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
[runtime] 2021-06-14 12:26:05 [error]: at System.RuntimeType.get_Namespace()
[runtime] 2021-06-14 12:26:05 [error]: at osu.Framework.Testing.RoslynTypeReferenceBuilder.<>c.<GetReferencedAssemblies>b__13_4(Type t)
[runtime] 2021-06-14 12:26:05 [error]: at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
[runtime] 2021-06-14 12:26:05 [error]: at osu.Framework.Testing.RoslynTypeReferenceBuilder.<GetReferencedAssemblies>g__addReference|13_1(Assembly assembly, Boolean force, <>c__DisplayClass13_0& )
[runtime] 2021-06-14 12:26:05 [error]: at osu.Framework.Testing.RoslynTypeReferenceBuilder.<GetReferencedAssemblies>b__13_0()
[runtime] 2021-06-14 12:26:05 [error]: at System.Threading.Tasks.Task`1.InnerInvoke()
[runtime] 2021-06-14 12:26:05 [error]: at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
[runtime] 2021-06-14 12:26:05 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[runtime] 2021-06-14 12:26:05 [error]: --- End of stack trace from previous location ---
[runtime] 2021-06-14 12:26:05 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[runtime] 2021-06-14 12:26:05 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[runtime] 2021-06-14 12:26:05 [error]: --- End of stack trace from previous location ---
[runtime] 2021-06-14 12:26:05 [error]: at osu.Framework.Testing.RoslynTypeReferenceBuilder.GetReferencedAssemblies(Type testType, String changedFile)
[runtime] 2021-06-14 12:26:05 [error]: at osu.Framework.Testing.DynamicClassCompiler`1.recompileAsync(Type targetType, String changedFile)
```

**Comment by bdach** [comment]
Am seeing similar, yet not the same. On my box I get:

```
[runtime] 2021-06-14 16:18:38 [error]: Error with dynamic compilation!
[runtime] 2021-06-14 16:18:38 [error]: System.IO.FileNotFoundException: Could not load file or assembly 'System.ComponentModel.Composition, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
[runtime] 2021-06-14 16:18:38 [error]: 
[runtime] 2021-06-14 16:18:38 [error]: File name: 'System.ComponentModel.Composition, Culture=neutral, PublicKeyToken=null'
```

In that case installing the package in manually *does* fix the issue. Unsure why this is happening. From what I can tell from `project.assets.json` output is that `NETStandard.Library/2.0.0` should be pulling it in but somehow didn't. Changing to a local framework checkout or dual-targeting netstandard didn't seem to help, however. No idea what this is other than *vague handwaving about dependency hell*.

**Comment by jai-x** [comment]
The problem was using `dotnet-core` as managed by the [`asdf` version manager](https://github.com/emersonsoares/asdf-dotnet-core).

This version seems to only install the `nuget` command line utils without the other classes as provided by the full [`Nuget.Client`](https://github.com/NuGet/NuGet.Client) package.

Switching to use the system provided `dotnet-core-sdk` resolves the issue.
