### ISSUE TITLE
`CurrentDisplayBindable` doesn't have a sane default

### ISSUE THREAD

**Issue by bdach** [ppy/osu-framework#5060]
This surfaced [after adding the dropdown for switching displays game-side](https://github.com/ppy/osu/discussions/17114) via a nullref:

```
2022-03-05 19:00:07 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2022-03-05 19:00:07 [error]: at osu.Framework.Platform.SDL2DesktopWindow.<SetupWindow>b__170_0(ValueChangedEvent`1 evt)
2022-03-05 19:00:07 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-03-05 19:00:07 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-03-05 19:00:07 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-03-05 19:00:07 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-03-05 19:00:07 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2022-03-05 19:00:07 [error]: at osu.Framework.Bindables.Bindable`1.SetDefault()
```

Indeed, `Display` is a reference type, and as such a `Bindable<Display>`'s default value is null.

The laziest way to fix is the following:

```diff
diff --git a/osu.Framework/Platform/SDL2DesktopWindow.cs b/osu.Framework/Platform/SDL2DesktopWindow.cs
index 01436bee85..f1f97cf971 100644
--- a/osu.Framework/Platform/SDL2DesktopWindow.cs
+++ b/osu.Framework/Platform/SDL2DesktopWindow.cs
@@ -1168,6 +1168,7 @@ private MouseButton mouseButtonFromEvent(byte button)
 
         public void SetupWindow(FrameworkConfigManager config)
         {
+            CurrentDisplayBindable.Default = PrimaryDisplay;
             CurrentDisplayBindable.ValueChanged += evt =>
             {
                 windowDisplayIndexBindable.Value = (DisplayIndex)evt.NewValue.Index;
```

but the above does not potentially handle cases where the primary display changes mid-game. Unsure if that should be handled or whether to start with just the above; looking for opinions on this.

**Comment by frenzibyte** [comment]
An alternative direction would be to consider `null` as a fallback value for using the primary monitor, along with adding a menu item for it similar to the audio device selection dropdown ("Primary display" or something). That way may be able handle against mid-game primary display changes.

**Comment by bdach** [comment]
that's not a great solution in my view because it forces every single framework consumer to add explicit handling for null.

i guess you could subscribe to `ValueChanged` and correct every `null` set to `PrimaryDisplay` but i'm not sure about that either.

**Comment by frenzibyte** [comment]
I think for simplicity what you have works best, can't imagine the magic "Primary Display" value working well when you change between displays anyways.

**Comment by peppy** [comment]
I'm fine with the proposed solution. Primary display changing while the game is running is something that one in one million will experience, and it will be resolved by restarting the game (probably normal for most games) so isn't a huge deal.
