### ISSUE TITLE
Disposed drawable can get a `FocusLostEvent` if removed while focused

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-framework#5156]
Discovered when working on https://github.com/ppy/osu-framework/pull/5150#discussion_r863843183, when moving things from `unbindInput()` to `OnFocusLost()` and `Dispose()`.

Another way to put it: `InputManager.FocusedDrawable` can hold a disposed drawable.

Since focus is only updated when input manger updates, the disposed and focused drawable gets unfocused in `unfocusIfNoLongerValid()` and receives the focus loss event.

Lowering the update rate in the test will increase the failure rate.

Failure from the test below:

```
2022-05-04 19:51:23 [verbose]: 🔸 Step #20 click
2022-05-04 19:51:23 [debug]: ClickEvent(Left) handled by textbox 3(BasicTextBox).
2022-05-04 19:51:23 [debug]: Focus changed from nothing to textbox 3(BasicTextBox).
2022-05-04 19:51:23 [debug]: MouseClick handled by textbox 3(BasicTextBox).
2022-05-04 19:51:23 [verbose]: 🔸 Step #21 textbox focused
2022-05-04 19:51:23 [verbose]: 🔸 Step #22 clear and dispose children
2022-05-04 19:51:23 [debug]: Focus on "textbox 3(BasicTextBox)" no longer valid as a result of unfocusIfNoLongerValid.
2022-05-04 19:52:45 [error]: An unhandled error has occurred.
2022-05-04 19:52:45 [error]: NUnit.Framework.AssertionException: textbox "textbox 3" disposed:
2022-05-04 19:52:45 [error]: at osu.Framework.Logging.ThrowingTraceListener.Fail(String message1, String message2) in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Logging\ThrowingTraceListener.cs:line 25
2022-05-04 19:52:45 [error]: at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
2022-05-04 19:52:45 [error]: at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)
2022-05-04 19:52:45 [error]: at System.Diagnostics.Debug.Fail(String message, String detailMessage)
2022-05-04 19:52:45 [error]: at System.Diagnostics.Debug.Assert(Boolean condition, String message)
2022-05-04 19:52:45 [error]: at osu.Framework.Graphics.UserInterface.TextBox.OnFocusLost(FocusLostEvent e) in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Graphics\UserInterface\TextBox.cs:line 1193
2022-05-04 19:52:45 [error]: at osu.Framework.Graphics.UserInterface.BasicTextBox.OnFocusLost(FocusLostEvent e) in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Graphics\UserInterface\BasicTextBox.cs:line 80
2022-05-04 19:52:45 [error]: at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e) in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Graphics\Drawable.cs:line 2013
2022-05-04 19:52:45 [error]: at osu.Framework.Input.InputManager.ChangeFocus(Drawable potentialFocusTarget, InputState state) in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Input\InputManager.cs:line 397
2022-05-04 19:52:45 [error]: at osu.Framework.Input.InputManager.ChangeFocus(Drawable potentialFocusTarget) in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Input\InputManager.cs:line 371
2022-05-04 19:52:45 [error]: at osu.Framework.Input.InputManager.unfocusIfNoLongerValid() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Input\InputManager.cs:line 913
2022-05-04 19:52:45 [error]: at osu.Framework.Input.InputManager.Update() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Input\InputManager.cs:line 433
2022-05-04 19:52:45 [error]: at osu.Framework.Input.PassThroughInputManager.Update() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Input\PassThroughInputManager.cs:line 143
2022-05-04 19:52:45 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Graphics\Drawable.cs:line 483
2022-05-04 19:52:45 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 899
2022-05-04 19:52:45 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c) in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 945
2022-05-04 19:52:45 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 926
2022-05-04 19:52:45 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.updateChild(Drawable c) in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 945
...
```

```cs
// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

using NUnit.Framework;
using osu.Framework.Graphics.UserInterface;
using osu.Framework.Testing;
using osuTK;
using osuTK.Input;

namespace osu.Framework.Tests.Visual.Drawables
{
    public class TestSceneDisposedFocus : ManualInputManagerTestScene
    {
        [TestCase(1)]
        [TestCase(2)]
        [TestCase(3)]
        [TestCase(4)]
        public void TestDisposedFocus(int i)
        {
            AddStep("set text box", () => Child = new BasicTextBox
            {
                Name = $"textbox {i}",
                Size = new Vector2(200, 20),
            });

            AddStep("move mouse to", () => InputManager.MoveMouseTo(Child));
            AddStep("click", () => InputManager.Click(MouseButton.Left));
            AddAssert("textbox focused", () => Child.HasFocus);
            AddStep("clear and dispose children", () => Clear(true));
        }
    }
}
```

```diff
diff --git a/osu.Framework/Graphics/UserInterface/TextBox.cs b/osu.Framework/Graphics/UserInterface/TextBox.cs
index f74595d31..9cc9925e1 100644
--- a/osu.Framework/Graphics/UserInterface/TextBox.cs
+++ b/osu.Framework/Graphics/UserInterface/TextBox.cs
@@ -1187,6 +1187,8 @@ protected override void OnMouseUp(MouseUpEvent e)
 
         protected override void OnFocusLost(FocusLostEvent e)
         {
+            Debug.Assert(!IsDisposed, $"textbox \"{Name}\" disposed");
+
             // let's say that a focus loss is not a user event as focus is commonly indirectly lost.
             FinalizeImeComposition(false);

 ```

**Comment by frenzibyte** [comment]
I believe going by what's covered for [input events](https://github.com/ppy/osu-framework/blob/c30feee6c4c4a42370c4f46f6d32165469b55409/osu.Framework.Tests/Input/MouseInputTest.cs#L18-L42), focus loss events should not be triggered on disposed drawables (by just not raising that in `InputManager`). If the drawable needs to perform finalisation steps at that point, then it should do that on disposal instead.

**Comment by smoogipoo** [comment]
Sounds dangerous, I suppose this also means that Drawables which are no longer in the hierarchy but not necessarily disposed retain focus?

**Comment by Susko3** [comment]
Removed drawables retain focus until `InputManager` updates and `unfocusIfNoLongerValid()` is called. I guess this is fine?

Should the focus be immediately lost when removed? This will probably fix the dispose problem, as disposal happens after drawables are removed.

**Comment by smoogipoo** [comment]
Hmm... Broadly speaking I'd say that's an expectation of any input event, not just focus. We'd need to see how other UI systems (browsers in specific) handle this scenario - do they e.g. invoke `OnKeyUp()` if an object is removed from the DOM?

**Comment by ekrctb** [comment]
As far as I researched, in DOM, removed elements don't get `blur` or `keyup` events.
More generally, a blur event is not dispatched if the old focused element is no longer [focusable](https://html.spec.whatwg.org/multipage/interaction.html#focusable-area).

[unfocusing steps](https://html.spec.whatwg.org/multipage/interaction.html#unfocusing-steps):

> If old focus target is not a [focusable area](https://html.spec.whatwg.org/multipage/interaction.html#focusable-area), then return.
> ...
> ... run the [focus update steps](https://html.spec.whatwg.org/multipage/interaction.html#focus-update-steps) with old chain, an empty list, and null respectively.

For example, if an input element is disabled while having a focus, the focus is gone but no blur event is dispatched to the element. Not sure this behavior is desirable for osu!framework.

Another thing to consider is that osu!framework directly trigger `FocusEvent` to the node <https://github.com/ppy/osu-framework/blob/a379f77079502a8ccf3cf80832350fa88f5e987e/osu.Framework/Input/InputManager.cs#L409>
But in browsers, dispatching an event is always subject to the capturing behavior so the event "descends" from the root, at least semantically.

**Comment by smoogipoo** [comment]
Hmm, so what would happen if they were to be added back and held states relating to the "down" input event? The document doesn't seem to touch upon that. Should they then get "up" events?

In principle I don't disagree with not propagating "up" events to removed drawables.

**Comment by peppy** [comment]
Do drawables already get a notification when they are removed? Or put another way, are we talking about being removed from a direct parent or potentially in a nested scenario (which is a case we've had to work around many times already).

If the latter, it would be hard to reset state..

**Comment by smoogipoo** [comment]
It would have to be the potentially nested scenario. We have a parent invalidation so we could use some cached layout value to tell if it's rooted, and I wouldn't expect this to be too expensive.

**Comment by ekrctb** [comment]
Details of DOM input events seem (intentionally?) unspecified, but `keydown` and `keyup` events don't necessary match each other, so an input element receives `keyup` without `keydown` if the element is focused while a key is pressed, for example.
This is very different from the current osu!framework's semantics where each key has a [`KeyEventManager`](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Input/KeyEventManager.cs) and `KeyUp` is only triggered for a drawable that handled the corresponding `KeyDown` event.
So I think DOM keydown/keyup events are not a good comparison.

I tested and WPF's KeyDown and KeyUp events have similar behavior (removed/disabled nodes don't get keyup event).
However, [mouse capturing](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.mouse.capture?view=windowsdesktop-6.0) is more semantically similar to the current osu!framework behavior (automatic capturing).
I tested and a removed/disabled node doesn't get `MouseUp` event. However, the [`LostMouseCapture`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.mouse.lostmousecapture?view=windowsdesktop-6.0) event is always triggered when a node is removed/disabled.

Perhaps, the input manager should be notified when a drawable currently "capturing" a keyboard key / a mouse button is removed / no longer valid, and remove the capturing.
