### ISSUE TITLE
`Host.Window.RequestClose()` is unsafe to call in single threaded mode

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-framework#5193]
Calling `Window.RequestClose()` in single threaded mode will lead to `threadRunner` running a frame within a frame.
In multithreaded, [this ](https://github.com/ppy/osu-framework/blob/f932f8df053f0011d755c95ad9a2ed61b94d136b/osu.Framework/Platform/GameHost.cs#L413) will just block on the input thread until the update thread runs once and the outcome of `Exiting` is determined.

The following stack trace and log can be reproduced by pressing Alt+F4 (Cmd+W) while in single threaded mode.
Order of events:
- `UserInputManager` at `(1)` updates and does a foreach over `GetPendingInputs()`
- the keydown for Alt+F4 is handled:
  - `Game` handles it and calls `Window.RequestClose()`
  - `SDL2DesktopWindow` immediately calls `GameHost.OnExitRequested` (even though the call is [supposedly scheduled](https://github.com/ppy/osu-framework/blob/0b4522ebf8f47bdd9e19053e56ad08e94ac8912e/osu.Framework/Platform/SDL2DesktopWindow.cs#L591))
  - this [runs a new (update) frame](https://github.com/ppy/osu-framework/blob/f932f8df053f0011d755c95ad9a2ed61b94d136b/osu.Framework/Platform/GameHost.cs#L411) (this is already really questionable behaviour)
  - this frame runs just fine, `UserInputManager` at `(2)` updates (and clears the `GetPendingInputs()` list)
- the original Alt+F4 had finally been handled, so the foreach looks for the next pending input, and throws `InvalidOperationException: Collection was modified; enumeration operation may not execute.`

```cs
2022-05-23 15:59:47 [verbose]: Host execution state changed to Stopping
2022-05-23 15:59:47 [debug]: Pressed (Exit) handled by VisualTestGame.
2022-05-23 15:59:47 [debug]: KeyDownEvent(F4, False) handled by PlatformActionContainer.
2022-05-23 15:59:47 [error]: An unhandled error has occurred.
2022-05-23 15:59:47 [error]: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
2022-05-23 15:59:47 [error]: at System.Collections.Generic.List`1.Enumerator.MoveNext()
2022-05-23 15:59:47 [error]: at osu.Framework.Input.InputManager.Update() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Input\InputManager.cs:line 443
2022-05-23 15:59:47 [error]: at osu.Framework.Input.PassThroughInputManager.Update() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Input\PassThroughInputManager.cs:line 143
2022-05-23 15:59:47 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Graphics\Drawable.cs:line 483
2022-05-23 15:59:47 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 899
2022-05-23 15:59:47 [error]: at osu.Framework.Platform.GameHost.UpdateFrame() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Platform\GameHost.cs:line 453
2022-05-23 15:59:47 [error]: at osu.Framework.Threading.GameThread.processFrame() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Threading\GameThread.cs:line 450
2022-05-23 15:59:47 [verbose]: Host execution state changed to Stopped
```

![image](https://user-images.githubusercontent.com/16479013/169862012-abbf389d-e3ae-4701-ab1a-b736dac3cbbd.png)

Properly scheduling the "event" fixes this. As scheduling simulates the window close button (called from the event loop, so no nested `threadRunner` frames).
```diff
diff --git a/osu.Framework/Platform/SDL2DesktopWindow.cs b/osu.Framework/Platform/SDL2DesktopWindow.cs
index b4da7aa52..dc7528d6b 100644
--- a/osu.Framework/Platform/SDL2DesktopWindow.cs
+++ b/osu.Framework/Platform/SDL2DesktopWindow.cs
@@ -588,7 +588,7 @@ private void updateWindowSize()
         /// <summary>
         /// Attempts to close the window.
         /// </summary>
-        public void RequestClose() => ScheduleEvent(() =>
+        public void RequestClose() => EventScheduler.Add(() =>
         {
             if (ExitRequested?.Invoke() != true)
                 Close();
```

**Comment by frenzibyte** [comment]
This raises the question of whether `ScheduleEvent` is actually operating properly currently, as it allows executing the action immediately if it's on the same thread, but that could mean events potentially performed at an unexpected time.

Is there a case where an event needs to be raised immediately rather than on the event scheduler loop? If so, would be better to mention that in `ScheduleEvent`'s xmldoc.

Other than that, I think the proposed solution makes sense, unless this could be vastly simplified with #5194 (I'm still not sure about the details of that one).
