### ISSUE TITLE
`System.Globalization.CultureNotFoundException` when setting invalid locale via config

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-framework#5328]
Noticed while using the `debug` locale in osu!, as it would crash on startup in release build. 

```cs
2022-07-31 13:13:35 [error]: An unhandled error has occurred.
2022-07-31 13:13:35 [error]: System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')
2022-07-31 13:13:35 [error]: debug is an invalid culture identifier.
2022-07-31 13:13:35 [error]: at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
2022-07-31 13:13:35 [error]: at osu.Framework.Localisation.LocalisationManager.updateLocale(ValueChangedEvent`1 locale)
2022-07-31 13:13:35 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2022-07-31 13:13:35 [error]: at osu.Framework.Bindables.Bindable`1.TriggerChange()
2022-07-31 13:13:35 [error]: at osu.Game.OsuGame.LoadComplete()
2022-07-31 13:13:35 [error]: at osu.Desktop.OsuGameDesktop.LoadComplete()
2022-07-31 13:13:35 [error]: at osu.Framework.Graphics.Drawable.loadComplete()
2022-07-31 13:13:35 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2022-07-31 13:13:35 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-31 13:13:35 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-31 13:13:35 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-31 13:13:35 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-31 13:13:35 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2022-07-31 13:13:35 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2022-07-31 13:13:35 [error]: at osu.Framework.Threading.GameThread.processFrame()
```

## Crashing line:

https://github.com/ppy/osu-framework/blob/9e9e476cf0321e3282e8c92805511fe5a6b8e60f/osu.Framework/Localisation/LocalisationManager.cs#L94

Adding try-catch here makes sense, defaulting to `CultureInfo.CurrentCulture` on `CultureNotFoundException`. This works, but is a bit weird as it leaves `FrameworkSetting.Locale` with the invalid locale. I would maybe expect the locale to reset to `string.Empty` on failure.

## Repro case:

```diff
diff --git a/osu.Framework.Tests/Localisation/LocalisationTest.cs b/osu.Framework.Tests/Localisation/LocalisationTest.cs
index f689e926e..bf0facd89 100644
--- a/osu.Framework.Tests/Localisation/LocalisationTest.cs
+++ b/osu.Framework.Tests/Localisation/LocalisationTest.cs
@@ -445,6 +445,12 @@ public void TestFormatComplexStringUsesFallbackFormatWithTranslatedParts()
             Assert.AreEqual("12.34 / number 98.76% EN / number romanised EN", text.Value);
         }

+        [Test]
+        public void TestInvalidLocale()
+        {
+            config.SetValue(FrameworkSetting.Locale, "invalid locale");
+        }
+
         private class FakeFrameworkConfigManager : FrameworkConfigManager
         {
             protected override string Filename => null;
```

**Comment by frenzibyte** [comment]
I'm not sure if this is platform-specific between debug/release builds, but I've had to set the following envvar to get the exception even when running a deployed build: `DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY=1`.
