### ISSUE TITLE
`SDL Error: Failed loading vulkan-1.dll: The specified module could not be found.` when using vulkan on windows

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-framework#5702]
```cs
2023-03-23 20:27:44 [verbose]: 🖼️ Configuration renderer choice: Vulkan
2023-03-23 20:27:44 [verbose]: 🖼️ Renderer fallback order: [ Vulkan, Direct3D 11, OpenGL (Legacy), OpenGL ]
2023-03-23 20:27:44 [verbose]: 🖼️ Initialising "Veldrid" renderer with "Vulkan" surface
2023-03-23 20:27:44 [verbose]: SDL error log [debug]: Unexpected controller element crc
2023-03-23 20:27:44 [verbose]: SDL error log [debug]: Failed loading vulkan-1.dll: The specified module could not be found.
2023-03-23 20:27:44 [verbose]: 🖼️ Renderer initialisation failed with:
2023-03-23 20:27:44 [verbose]: System.InvalidOperationException: Failed to create SDL window. SDL Error: Failed loading vulkan-1.dll: The specified module could not be found.
2023-03-23 20:27:44 [verbose]: at osu.Framework.Platform.SDL2DesktopWindow.Create() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Platform\SDL2DesktopWindow.cs:line 233
2023-03-23 20:27:44 [verbose]: at osu.Framework.Platform.Windows.WindowsWindow.Create() in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Platform\Windows\WindowsWindow.cs:line 65
2023-03-23 20:27:44 [verbose]: at osu.Framework.Platform.GameHost.SetupRendererAndWindow(IRenderer renderer, GraphicsSurfaceType surfaceType) in C:\Users\Mateo\code\git\osu-framework\osu.Framework\Platform\GameHost.cs:line 961
2023-03-23 20:27:44 [important]: The selected renderer (Vulkan) failed to initialise. Renderer selection has been reverted to automatic.
```

GPU: AMD Radeon R7 370

Copying a random `vulkan-1.dll` to the output folder works.
Most programs on my PC seem to ship with `vulkan-1.dll`, so I guess we need to ship this as a native library as well.

**Comment by smoogipoo** [comment]
Drivers typically include the Vulkan loader DLL, but it seems like it’s acceptable to redistribute it as per https://vulkan.lunarg.com/issue/view/5784e0485698c020d7157ce9
