### ISSUE TITLE
NullReferenceException when accessing ScreenSpaceDrawQuad

### ISSUE THREAD

**Issue by nobbele** [ppy/osu-framework#5792]
not being able to access `ScreenSpaceDrawQuad` when `IsLoaded == true` seems like a bug to me. 
Parent is null, I assume it gets initialized too late?

Relevant stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at osu.Framework.Graphics.Containers.CompositeDrawable.get_BoundingBox()
at osu.Framework.Graphics.Drawable.computeRequiredParentSizeToFit()
at osu.Framework.Graphics.Containers.CompositeDrawable.computeAutoSize()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateAutoSize()
at osu.Framework.Graphics.Containers.CompositeDrawable.updateChildrenSizeDependencies()
at osu.Framework.Graphics.Containers.CompositeDrawable.get_Size()
at osu.Framework.Graphics.Drawable.get_DrawSize()
at osu.Framework.Graphics.Drawable.ComputeScreenSpaceDrawQuad()
at osu.Framework.Graphics.Drawable.get_ScreenSpaceDrawQuad()
```

**Comment by smoogipoo** [comment]
How/where are you seeing this come up?

**Comment by nobbele** [comment]
It's running inside `Scheduler.AddDelayed(f, dt, repeat: true)`'s handler `f`
The Drawable gets added to the list used inside `f` at the end of it's `[BackgroundDependencyLoader] load`

Can `f` be ran after `IsLoaded = true` but before `Parent = xx` due to threading perhaps?

**Comment by smoogipoo** [comment]
I'm not entirely seeing how this is possible. Are you working on a personal project with osu!framework and hitting this? If so, can you post a trimmed down example that causes it to happen?

I haven't been able to reproduce this with this simple test:

```csharp
public partial class TestSceneTesting : FrameworkTestScene
{
    [Test]
    public void TestAddDrawable()
    {
        AddStep("add drawable", () => Add(new TestDrawable()));
    }

    private partial class TestDrawable : CompositeDrawable
    {
        [BackgroundDependencyLoader]
        private void load()
        {
            Drawable autoSizedDrawable;
            InternalChild = autoSizedDrawable = new Container
            {
                AutoSizeAxes = Axes.Both,
                Child = new Container
                {
                    AutoSizeAxes = Axes.Both,
                    Child = new Box { Size = new Vector2(100) }
                }
            };

            Scheduler.Add(() => Trace.Assert(autoSizedDrawable.DrawSize.X == 100));
        }
    }
}
```
